services:
  - type: web
    name: abavandimwe
    runtime: python
    repo: https://github.com/Mdav10/abavandimwe
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8080
    autoDeploy: true
